Game1:
  world: World
  timer: 60
  lightSwitchMin: 1
  lightSwitchMax: 5
  spawn:
    ==: org.bukkit.Location
    world: World
    x: -819.0
    y: 4.0
    z: 409.0
    pitch: 0.0
    yaw: 0.0
  barrier:
    first_point:
      x: -790.0
      y: 3.0
      z: 415.0
    second_point:
      x: -850.0
      y: 7.0
      z: 415.0
  killzone:
    first_point:
      x: -789.0
      y: 22.0
      z: 510.0
    second_point:
      x: -850.0
      y: 22.0
      z: 415.0
  goal:
    first_point:
      x: -850.0
      y: 4.0
      z: 511.0
    second_point:
      x: -789.0
      y: 22.0
      z: 537.0
  doll:
    first_point:
      x: -850.0
      y: 4.0
      z: 511.0
    second_point:
      x: -789.0
      y: 22.0
      z: 537.0
Game3:
  world: World
  timer: 60
  lightSwitchOn: 1
  lightSwitchOff: 8
Game6:
  world: World
  timer: 60
  spawn:
    ==: org.bukkit.Location
    world: World
    x: -819.0
    y: 4.0
    z: 409.0
    pitch: 0.0
    yaw: 0.0
  glass:
    first_point:
      x: -790.0
      y: 3.0
      z: 415.0
    second_point:
      x: -850.0
      y: 7.0
      z: 415.0
  goal:
    first_point:
      x: -850.0
      y: 4.0
      z: 511.0
    second_point:
      x: -789.0
      y: 22.0
      z: 537.0
min-players: 2
max-players: 12
intermission-time: 10
start-time: 30
Lobby:
  ==: org.bukkit.Location
  world: World
  x: -809.0
  y: 4.0
  z: 88.0
  yaw: 0.0
  pitch: 0.0
rewards:
    - say {winner} is the winner!
    - eco give {winner} 10
