Game1:
  world: World
  timer: 60
  lightSwitchMin: 1
  lightSwitchMax: 5
  spawn:
    ==: org.bukkit.Location
    world: World
    x: -819.1051015526494
    y: 4.0
    z: 405.0058338699251
    pitch: -3.5609317
    yaw: 3.9092407
  barrier:
    first_point:
      x: -790.0
      y: 3.0
      z: 415.0
    second_point:
      x: -850.0
      y: 7.0
      z: 415.0
  killzone:
    first_point:
      x: -789.0
      y: 22.0
      z: 510.0
    second_point:
      x: -850.0
      y: 22.0
      z: 415.0
  goal:
    first_point:
      x: -850.0
      y: 4.0
      z: 511.0
    second_point:
      x: -789.0
      y: 22.0
      z: 537.0
Game2:
  world: World
  timer: 60
  spawn:
    ==: org.bukkit.Location
    world: World
    x: -819.1051015526494
    y: 4.0
    z: 405.0058338699251
    pitch: -3.5609317
    yaw: 3.9092407
  cuboid:
    first_point:
      x: -790.0
      y: 3.0
      z: 415.0
    second_point:
      x: -850.0
      y: 7.0
      z: 415.0
Game3:
  world: World
  timer: 60
  lightSwitchOn: 1
  lightSwitchOff: 8
Game4:
  world: World
  spawn_red:
    ==: org.bukkit.Location
    world: World
    x: -1119.4612904484902
    y: 34.0
    z: 759.526055253015
    pitch: -0.22597487
    yaw: -0.13092041
  spawn_blue:
    ==: org.bukkit.Location
    world: World
    x: -1119.4561858823017
    y: 34.0
    z: 816.988663666825
    pitch: -1.9340928
    yaw: -179.8451
  barrier:
    first_point:
      x: -1120.0
      y: 33.0
      z: 793.0
    second_point:
      x: -1120.0
      y: 36.0
      z: 783.0
Game6:
  world: World
  timer: 60
  material: LIGHT_GRAY_STAINED_GLASS
  spawn:
    ==: org.bukkit.Location
    world: World
    x: -228.21945388401338
    y: 95.0
    z: 973.5909721586725
    pitch: -3.1099277
    yaw: -179.62915
  barrier:
    first_point:
      x: -1120.0
      y: 33.0
      z: 793.0
    second_point:
      x: -1120.0
      y: 36.0
      z: 783.0
  glass:
    first_point:
      x: -231.0
      y: 94.0
      z: 963.0
    second_point:
      x: -226.0
      y: 94.0
      z: 902.0
  goal:
    first_point:
      x: -258.0
      y: 94.0
      z: 900.0
    second_point:
      x: -199.0
      y: 109.0
      z: 888.0
  goal_blue:
    first_point:
      x: -1115.0
      y: 39.0
      z: 825.0
    second_point:
      x: -1123.0
      y: 33.0
      z: 794.0
  goal_red:
    first_point:
      x: -1123.0
      y: 33.0
      z: 782.0
    second_point:
      x: -1115.0
      y: 39.0
      z: 751.0
Game7:
  world: World
  kill-block: sand
  spawn:
    ==: org.bukkit.Location
    world: World
    x: -856.8846014602562
    y: 4.0
    z: 793.5736121061759
    pitch: -2.609787
    yaw: 85.251465
min-players: 2
max-players: 12
intermission-time: 30
endgame-time: 5
start-time: 30
eliminate-players: true
Lobby:
  ==: org.bukkit.Location
  world: World
  x: -809.0
  y: 4.0
  z: 88.0
  pitch: 0.0
  yaw: 0.0
rewards:
  - say %squidgame_arena_winner% is the winner!
  - eco give %squidgame_arena_winner% 10
