Game1:
  world: World
  timer: 60
  lightSwitchMin: 1
  lightSwitchMax: 5
  spawn:
    ==: org.bukkit.Location
    world: World
    x: -819.0
    y: 4.0
    z: 409.0
    pitch: 0.0
    yaw: 0.0
  barrier:
    first_point:
      x: -790.0
      y: 3.0
      z: 415.0
    second_point:
      x: -850.0
      y: 7.0
      z: 415.0
  killzone:
    first_point:
      x: -789.0
      y: 22.0
      z: 510.0
    second_point:
      x: -850.0
      y: 22.0
      z: 415.0
  goal:
    first_point:
      x: -850.0
      y: 4.0
      z: 511.0
    second_point:
      x: -789.0
      y: 22.0
      z: 537.0
Game3:
  world: World
  timer: 60
  lightSwitchOn: 1
  lightSwitchOff: 8
Game4:
  world: World
  timer: 60
  spawn_red:
    ==: org.bukkit.Location
    world: World
    x: -227.94925437318383
    y: 95.0
    z: 972.1857812621586
    pitch: -3.265213
    yaw: -179.7325
  spawn_blue:
    ==: org.bukkit.Location
    world: World
    x: -227.94925437318383
    y: 95.0
    z: 972.1857812621586
    pitch: -3.265213
    yaw: -179.7325
  goal_red:
    first_point:
      x: -258.0
      y: 94.0
      z: 900.0
    second_point:
      x: -199.0
      y: 109.0
      z: 888.0
  goal_blue:
    first_point:
      x: -258.0
      y: 94.0
      z: 900.0
    second_point:
      x: -199.0
      y: 109.0
      z: 888.0
  barrier:
    first_point:
      x: -790.0
      y: 3.0
      z: 415.0
    second_point:
      x: -850.0
      y: 7.0
      z: 415.0
Game6:
  world: World
  timer: 60
  material: LIGHT_GRAY_STAINED_GLASS
  spawn:
    ==: org.bukkit.Location
    world: World
    x: -227.94925437318383
    y: 95.0
    z: 972.1857812621586
    pitch: -3.265213
    yaw: -179.7325
  barrier:
    first_point:
      x: -790.0
      y: 3.0
      z: 415.0
    second_point:
      x: -850.0
      y: 7.0
      z: 415.0
  glass:
    first_point:
      x: -231.0
      y: 94.0
      z: 963.0
    second_point:
      x: -226.0
      y: 94.0
      z: 902.0
  goal:
    first_point:
      x: -258.0
      y: 94.0
      z: 900.0
    second_point:
      x: -199.0
      y: 109.0
      z: 888.0
Game7:
  world: World
  spawn_1:
    ==: org.bukkit.Location
    world: World
    x: -227.94925437318383
    y: 95.0
    z: 972.1857812621586
    pitch: -3.265213
    yaw: -179.7325
  spawn_2:
    ==: org.bukkit.Location
    world: World
    x: -227.94925437318383
    y: 95.0
    z: 972.1857812621586
    pitch: -3.265213
    yaw: -179.7325
min-players: 2
max-players: 12
intermission-time: 10
start-time: 30
Lobby:
  ==: org.bukkit.Location
  world: World
  x: -809.0
  y: 4.0
  z: 88.0
  yaw: 0.0
  pitch: 0.0
rewards:
    - say {winner} is the winner!
    - eco give {winner} 10
