name: SquidGame
version: '${version}'
main: com.soradgaming.squidgame.SquidGame
api-version: 1.17
softdepend: [ PlaceholderAPI ]
authors: [ SoRadGaming, Shinx ]
description: Squid Game Plugin for the UESL Minecraft Server
commands:
  squidgame:
    aliases: ["sg", "sq", "squid"]
    description: The main command for the plugin.
