name: SquidGame
version: '${version}'
main: com.soradgaming.squidgame.SquidGame
api-version: 1.18
depend: [WorldEdit]
softdepend: [PlaceholderAPI]
authors: [ SoRadGaming ]
description: Squid Game Plugin for Minecraft
commands:
  squidgame:
    aliases: ["sg", "sq", "squid"]
    description: The main command for the plugin.
  squidgamesetup:
    aliases: ["sgsetup", "sqsetup", "squidsetup"]
    description: The setup command for the plugin.
